import Link from "next/link";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Full Page Background */}
        <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50">
          {/* Header */}
          <header className="p-6 flex justify-between items-center bg-white shadow-lg rounded-b-lg">
            <h1 className="text-3xl font-extrabold text-gray-900">Manage Your LMS</h1>
            <div className="text-lg font-medium text-gray-600">Menu</div>
          </header>

          {/* Main content */}
          <div className="flex h-full">
            {/* Sidebar */}
            <nav className="w-60 bg-white shadow-lg rounded-tr-lg border-r border-gray-200 flex flex-col gap-4 p-6">
              <Link href="/admin" className="block p-3 text-gray-700 rounded-lg hover:bg-purple-100 hover:text-purple-900 transition duration-300 text-lg font-semibold">
                Dashboard
              </Link>
              <Link href="/admin/courses" className="block p-3 text-gray-700 rounded-lg hover:bg-purple-100 hover:text-purple-900 transition duration-300 text-lg font-semibold">
                Courses
              </Link>
              <Link href="/admin/batches" className="block p-3 text-gray-700 rounded-lg hover:bg-purple-100 hover:text-purple-900 transition duration-300 text-lg font-semibold">
                Batches
              </Link>
              <Link href="/admin/teachers" className="block p-3 text-gray-700 rounded-lg hover:bg-purple-100 hover:text-purple-900 transition duration-300 text-lg font-semibold">
                Teachers
              </Link>
            </nav>

            {/* Content Area */}
            <main className="flex-grow bg-white shadow-md rounded-tl-lg p-8 m-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
