import Link from "next/link";

export const metadata = {
  title: "LMS | COURSES",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <section className="min-h-screen bg-gray-50">
      {/* Navigation Bar */}
      <div className="bg-white py-6 shadow-md flex justify-center gap-10">
        <Link
          href="/courses/categories"
          className="text-gray-700 hover:text-purple-600 font-medium transition-all duration-300 ease-in-out"
        >
          Course Categories
        </Link>
        <Link
          href="/courses/trainers"
          className="text-gray-700 hover:text-purple-600 font-medium transition-all duration-300 ease-in-out"
        >
          Course Trainers
        </Link>
      </div>
      {/* Page Content */}
      <div className="p-10 mx-auto max-w-7xl">
        {children}
      </div>
    </section>
  );
}
